
AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the AWS Lambda function the provides the contact flow helper tools.
Parameters:
    AWSS3BucketPrefix:
      Type: String
      Default: ''
      Description: Not required and only used for development purposes.
    AWSRegion:
        Type: String
        Default: us-east-1
        AllowedValues:
          - us-east-1
          - us-west-2
          - ap-southeast-1
          - ap-southeast-2
          - ap-northeast-1
          - eu-central-1
          - eu-west-2
          - ca-central-1
        Description: The region code that you are deploying to. This should be the same region that your Amazon Connect instance is deployed to. MAKE SURE that you have your console currently set to this region.
    ConnectInstanceName:
        Type: String
        Default: REPLACEME
        Description: Provide the instance name for Amazon Connect.
    AWSSCVCommonRole:
        Type: String
        Default: REPLACEME
        Description: ARN of the awsscv_common_role role
Resources:
    awsscvcontactflowhelper:
        Type: AWS::Lambda::Function
        Properties:
          Code:
           S3Bucket:
              !Join
                - ''
                - - !Ref AWSS3BucketPrefix
                  - 'awsscv-supporting-code-'
                  - !Ref AWSRegion
           S3Key: awsscv_contact_flow_helper.zip
          Description: Baseline text and math functions for ease of access in contact flows.
          FunctionName:
            !Join
                - ''
                - - 'awsscv_contact_flow_helper_'
                  - !Ref ConnectInstanceName
          Handler: awsscv_contact_flow_helper.lambda_handler
          Role: !Ref AWSSCVCommonRole
          Runtime: python3.8
          Timeout: 8
