AWSTemplateFormatVersion: "2010-09-09"
Description: Establishes supporting layers for Service Cloud Voice tools, examples, and add-ons from AWS.
Parameters:
  AWSS3BucketPrefix:
    Type: String
    Default: ''
    Description: Not required and only used for development purposes.
  AWSRegion:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-west-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - eu-central-1
      - eu-west-2
      - ca-central-1
    Description: The region code that you are deploying to. MAKE SURE that you have your console currently set to this region. Must be a region that supports Service Cloud Voice.
Resources:
    SCVCommonPythonLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
          CompatibleRuntimes:
            - python3.8
            - python3.9
          Content:
            S3Bucket:
              !Join
                - ''
                - - !Ref AWSS3BucketPrefix
                  - 'awsscv-supporting-code-'
                  - !Ref AWSRegion
            S3Key: awsscv_python_common.zip
          Description: Provides dependencies code and functions for Python Lambda functions that augment the Service Cloud Voice offering from Salesforce
          LayerName: awsscv_common_python
          LicenseInfo: https://aws.amazon.com/apache-2-0
    SCVCommonNodeLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
          CompatibleRuntimes:
            - nodejs12.x
            - nodejs14.x
          Content:
            S3Bucket:
              !Join
                - ''
                - - !Ref AWSS3BucketPrefix
                  - 'awsscv-supporting-code-'
                  - !Ref AWSRegion
            S3Key: awsscv_nodejs_common.zip
          Description: Provides dependencies code and functions for node.js Lambda functions that augment the Service Cloud Voice offering from Salesforce
          LayerName: awsscv_common_node
          LicenseInfo: https://aws.amazon.com/apache-2-0
Outputs:
  SCVCommonPythonLayerARN:
    Description: ARN for the Python common layer
    Value: !Ref SCVCommonPythonLayer
  SCVCommonNodeLayerARN:
    Description: ARN for the node.js common layer
    Value: !Ref SCVCommonNodeLayer
